### Obtener todos los libros (paginado)
GET http://localhost:3000/api/books?page=1&limit=5

### Obtener libro por ID
GET http://localhost:3000/api/books/1

### Filtrar libros por búsqueda
GET http://localhost:3000/api/books?search=soledad

### Crear Libro
POST http://localhost:3000/api/books
Content-Type: application/json

{
    "titulo": "Libro de Prueba REST",
    "isbn": "999888777",
    "editorial": "Tech Books",
    "anyo_publicacion": 2024,
    "paginas": 150,
    "precio": 29.99,
    "imagen": "https://example.com/cover.jpg",
    "id_autor": 1
}

### Actualizar Libro
PUT http://localhost:3000/api/books/5
Content-Type: application/json

{
    "imagen": "https://imagessl8.casadellibro.com/a/l/s5/98/9788401352898.webp",
    "titulo": "La casa de los espíritus"
}

### Borrar Libro
DELETE http://localhost:3000/api/books/12